name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          show-versioninfo: true         # this causes versioninfo to be printed to the action log
      - uses: julia-actions/julia-buildpkg@latest
      - run:  julia --project -e 'using AdmitConfiguration, CSV; set_programs(joinpath(pkgdir(AdmitConfiguration), "examples", "WashU.csv"))'
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
